spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: adresse-mail
    password: mot-de-passe
    properties:
      mail:
#        debug: true
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
#https://github.com/m37-78/EmailSenderExample.git